command:
  switch:
    branch_name_template: JIRA-<%= branch_name %>
    exclude:
      - some_branch
      - some_other_branch
  cmt:
    subject_template: >
      <%=
        if branch_name.start_with?('JIRA-')
          "[#{branch_name}] #{subject}"
        else
          subject
        end
      %>
    body_template: >
      <%=
        if branch_name.start_with?('JIRA-')
          "http://myjira.com/#{branch_name}\n\n#{body}"
        else
          body
        end
      %>
alias:
  br: branch
  sw: switch
  l: log --oneline