#!/usr/bin/env ruby

# frozen_string_literal: true

$LOAD_PATH << File.expand_path('lib', __dir__)

require 'rlt'

begin
  Rlt::CLI.start(ARGV)
rescue TTY::Reader::InputInterrupt
  puts ''
  # ignore
rescue TTY::Command::ExitError
  puts ''
  # ignore
rescue Rlt::GitNativeCommandError
  Rlt::Utils::GitUtil.execute_native_command(ARGV)
end
