#!/usr/bin/env ruby

# frozen_string_literal: true

$LOAD_PATH << File.expand_path('lib', __dir__)

require 'rlt'

argv = Rlt::Alias.unpack(ARGV)

begin
  Rlt::CLI.start(argv)
rescue TTY::Reader::InputInterrupt
  puts ''
  # ignore
rescue TTY::Command::ExitError
  puts ''
  # ignore
rescue Rlt::GitNativeCommandError
  Rlt::Utils::GitUtil.execute_native_command(argv)
end
